#! /bin/bash

fileList=$(ls -p ~/ | grep -v / | grep -E "[0-9]{4}\-[0-9]{2}\-[0-9]{2}$")

dir=$(ls -d ~/*/ | awk -F '/' '{ print $(NF-1) }' |  grep -E "^Backup-[0-9]{4}\-[0-9]{2}\-[0-9]{2}$" | sort | awk -F '/' 'END{print $0}')

fileList=$(ls -p ~/${dir} | grep -v / | grep -v -E "[0-9]{4}\-[0-9]{2}\-[0-9]{2}$")


if ! [ -d ~/restore/ ]
then
    mkdir ~/restore
fi

for i in ${fileList[*]}
do
    #echo $i
    cp ~/${dir}/${i} ~/restore/
done
